name: model_train
permissions:
  id-token: write
  contents: write

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
        with:
         version: 'v0.18.1'

      # Setting up Node.js (you may want to ensure this is version 20, since older versions are deprecated)
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Set up CML
      - uses: iterative/setup-cml@v1

      # Python setup
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.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 }}  # Replace with your actual GitHub secret token name
        run: |
          # Install dependencies
          pip install -r requirements.txt
          
          # Run the training script
          python train_model.py
          
