name: model_train
permissions:
  id-token: write
  contents: write

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install cml scikit-learn pandas numpy seaborn matplotlib

    - name: Train model
      run: |
        python train_model.py
