name: model_train
permissions:
  id-token: write
  contents: write

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install CML manually
      run: |
        pip install iterative-cml  # Install CML separately

    - name: Train model
      env:
        REPO_TOKEN: ${{ secrets.G1nwg_TOKEN }}
      run: |
        python train_model.py
        
        echo "RF and LR Model score" > report.md
        cat report.txt >> report.md
        
        echo "Confusion Matrix & Feature Importance" > report1.md
        echo "![Confusion Matrix](./ConfusionMatrix.png)" >> report1.md
        echo "![Feature Importance](./FeatureImportance.png)" >> report1.md

        cat report.md report1.md > combined_file.md

        # Disable telemetry for CML
        export CML_TELEMETRY_DISABLED=true
        cml comment create combined_file.md
