name: model_train
permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: iterative/setup-cml@v1.1.1
    - uses: actions/checkout@v3
    
    - name: Train model
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install -r requirements.txt
        python train_model.py
        
        echo "RF and LR Model score" > report.md
        cat scores.txt >> report.md
        
        echo "Confusion Matrix & Feature Importance" > report1.md
        echo "![Confusion Matrix](./ConfusionMatrix.png)" >> report1.md
        echo "![Feature Importance](./FeatureImportance.png)" >> report1.md

        if [ ! -f report1.md ]; then
            echo "report1.md does not exist."
            exit 1
        fi

        cat report.md report1.md > combined_file.md
        
        if [ ! -f combined_file.md ]; then
            echo "combined_file.md does not exist."
            exit 1
        fi

        cml comment create combined_file.md
