name: model_train
permissions:
  id-token: write
  contents: write

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: iterative/setup-cml@v1
    - uses: actions/checkout@v3
    
    - name: Train model
      env:
        REPO_TOKEN: ${{ secrets.G1nwg_TOKEN }}
      run: |
        pip install -r requirements.txt
        python train_model.py
        
        echo "RF and LR Model score" > report.md
        cat report.txt >> report.md
        
        echo "Confusion Matrix & Feature Importance" > report1.md
        echo "![Confusion Matrix](./ConfusionMatrix.png)" >> report1.md
        echo "![Feature Importance](./FeatureImportance.png)" >> report1.md

        # Fixed typo: use 'report1.md' instead of 'reportl.md'
        cat report.md report1.md > combined_file.md
        cml comment create combined_file.md
