trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TrainModel
  steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true

    - script: |
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python train_model.py
      displayName: 'Train the model'

    - task: NodeTool@0
      inputs:
        versionSpec: '16'
      displayName: 'Set up Node.js'
